project:
  type: manuscript
  output-dir: docs

resources:
  - images

lang: de

manuscript:
  article: index.qmd

execute:
  freeze: auto
  fig-dir: "images"


format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt
#    lof: true
#    lot: true
    toc: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    keep-tex: true
    output-file: presentation